<?php
/**
 * List of all add-ons available for MailPoet
 */ 

$available_add_ons = array(
	array(
		'name' 				=> 'WooCommerce: Subscribe on Checkout',
		'search' 			=> 'MailPoet WooCommerce Add-on',
		'thumbnail' 		=> 'woocommerce.png',
		'description' 		=> __('Adds a checkbox on checkout page for your customers to subscribe to your MailPoet newsletters.'),
		'plugin_url' 		=> 'mailpoet-woocommerce-addon/mailpoet-woocommerce-addon.php',
		'version' 			=> '1.0.1',
		'config_url' 		=> 'admin.php?page=woocommerce_settings&tab=mailpoet',
		'official' 			=> 'yes',
		'on_wordpress.org' 	=> 'yes',
		'free' 				=> 'yes',
		'service' 			=> 'no',
		'requires' 			=> 'woocommerce/woocommerce.php',
	),
	array(
		'name' 				=> 'Jigoshop: Subscribe on Checkout',
		'search' 			=> 'MailPoet Jigoshop Add-on',
		'thumbnail' 		=> 'jigoshop.png',
		'description' 		=> __('Adds a checkbox on checkout page for your customers to subscribe to your MailPoet newsletters.'),
		'plugin_url' 		=> 'mailpoet-jigoshop-addon/mailpoet-jigoshop-addon.php',
		'version' 			=> '1.0.2',
		'config_url' 		=> 'admin.php?page=jigoshop_settings&tab=mailpoet',
		'official' 			=> 'yes',
		'on_wordpress.org' 	=> 'yes',
		'free' 				=> 'yes',
		'service' 			=> 'no',
		'requires' 			=> 'jigoshop/jigoshop.php',
	),
	array(
		'name' 				=> 'Gravity Forms: Subscribe Add-on',
		'search' 			=> 'MailPoet Gravity Forms Add-on',
		'thumbnail' 		=> 'gravity-forms.png',
		'description' 		=> __('Adds a new field to add to your forms so your visitors can subscribe to your MailPoet newsletters.'),
		'plugin_url' 		=> 'mailpoet-gravity-forms-addon/mailpoet-gravity-forms-addon.php',
		'version' 			=> '1.0.0',
		'official' 			=> 'yes',
		'on_wordpress.org' 	=> 'yes',
		'free' 				=> 'yes',
		'service' 			=> 'no',
		'requires' 			=> 'gravityforms/gravityforms.php',
	),
	array(
		'name' 				=> 'WP e-Commerce: Subscribe on Checkout',
		'search' 			=> 'MailPoet WP e-Commerce Add-on',
		'thumbnail' 		=> 'wp-e-commerce.png',
		'description' 		=> __('Adds a checkbox on checkout page for your customers to subscribe to your MailPoet newsletters.'),
		'plugin_url' 		=> 'mailpoet-wp-ecommerce-addon/mailpoet-wp-ecommerce-addon.php',
		'version' 			=> '1.0.0',
		'config_url' 		=> 'edit.php?post_type=wpsc-product&page=mailpoet',
		'official' 			=> 'yes',
		'on_wordpress.org' 	=> 'yes',
		'free' 				=> 'yes',
		'service' 			=> 'no',
		'requires' 			=> 'wp-e-commerce/wp-shopping-cart.php',
	),
	array(
		'name' 				=> 'Restrict Content Pro: Registration Add-on',
		'search' 			=> 'Restrict Content Pro Wysija',
		'thumbnail' 		=> 'pippins.png',
		'description' 		=> __('Add a checkbox on the registration form of this plugin so your new users join a list of your choice.'),
		'plugin_url' 		=> 'restrict-content-pro-wysija/rcp-wysija.php',
		'version' 			=> '1.0',
		'official' 			=> 'yes',
		'on_wordpress.org' 	=> 'yes',
		'free' 				=> 'yes',
		'service' 			=> 'no',
		'requires' 			=> 'restrict-content-pro/restrict-content-pro.php',
	),
	array(
		'name' 				=> 'Contact Form 7: MailPoet Add-on',
		'search' 			=> 'MailPoet Contact Form 7',
		'thumbnail' 		=> 'cf7.png',
		'description' 		=> __('Add of checkbox in your forms, and choose which lists the user gets added to.'),
		'plugin_url' 		=> 'mailpoet-contact-form-7/mailpoet-contact-form-7.php',
		'author_url' 		=> '',
		'version' 			=> '1.0.0',
		'official' 			=> 'yes',
		'on_wordpress.org' 	=> 'yes',
		'free' 				=> 'yes',
		'service' 			=> 'no',
		'requires' 			=> 'contact-form-7/wp-contact-form-7.php',
	),
	
	array(
		'name' 				=> 'WangGuard - MailPoet Connector',
		'search' 			=> 'WangGuard - Wysija Newsletter Connector',
		'thumbnail' 		=> 'wangguard.png',
		'description' 		=> __('Verify MailPoet subscribers before adding them to your MailPoet subscribers list by checking against the WangGuard service that each new subscriber is not reported as a known Splogger or unwanted user.'),
		'review' 			=> __('If you have this problem, then this is your solution. Totally free too.'),
		'plugin_url' 		=> 'wangguard-wysija-newsletter-connector/wangguard-wysija.php',
		'author_url' 		=> 'http://clicky.me/wangguard',
		'version' 			=> '1.0.0',
		'official' 			=> 'yes',
		'on_wordpress.org' 	=> 'yes',
		'free' 				=> 'yes',
		'service' 			=> 'no',
		'requires' 			=> '',
	),
	
	array(
		'name' 				=> 'IssueM - Leaky Paywall - MailPoet Add-on',
		'search' 			=> 'IssueM - Leaky Paywall - MailPoet Add-on',
		'thumbnail' 		=> 'leakypw.png',
		'description' 		=> __('Leaky Paywall is a Premium plugin to put content behind a paywall. This add-on manages your customers\' customers subscriptions.'),
		'plugin_url' 		=> 'leaky-paywall-mail-poet/issuem-leaky-paywall-mailpoet.php',
		'author_url' 		=> 'http://clicky.me/leakypw',
		'version' 			=> '1.0.0',
		'official' 			=> 'yes',
		'on_wordpress.org' 	=> 'yes',
		'free' 				=> 'yes',
		'service' 			=> 'no',
	),
	
	/* Below is the list of services that work with MailPoet */
	
	array(
		'name' 				=> 'OptinMonster: Slick Forms',
		'search' 			=> 'OptinMonster: slick forms',
		'thumbnail' 		=> 'optinmonster.png',
		'description' 		=> __('Put a subscription form in a popup, footer bar or slide-in to add subscribers with this Premium plugin.'),
		'review' 			=> __('The authors have done a pretty awesome job.'),
		'plugin_url' 		=> '',
		'author_url' 		=> 'http://clicky.me/optinmonsteraddon',
		'purchase_url' 		=> '',
		'version' 			=> '',
		'official' 			=> 'no',
		'on_wordpress.org' 	=> 'no',
		'free' 				=> 'no',
		'service' 			=> 'yes',
		'premium_offer' 	=> __('No coupon available.'),
	),
	
	array(
		'name' 				=> 'Pippity: Form in a Popup',
		'search' 			=> 'Pippity: form in a popup',
		'thumbnail' 		=> 'pippity.png',
		'description' 		=> __('This Premium plugin allows you to add a MailPoet form in a popup.'),
		'review' 			=> __('You\'ll need to know CSS to design it to your taste.'),
		'plugin_url' 		=> '',
		'author_url' 		=> 'http://clicky.me/pippity',
		'purchase_url' 		=> '',
		'version' 			=> '',
		'official' 			=> 'no',
		'on_wordpress.org' 	=> 'no',
		'free' 				=> 'no',
		'service' 			=> 'yes',
		'premium_offer' 	=> '',
	),
	
	array(
		'name' 				=> 'Hybrid Connect: Forms and Facebook',
		'search' 			=> 'Hybrid Connect: forms and Facebook',
		'thumbnail' 		=> 'hybrid-connect.png',
		'description' 		=> __('This Premium plugin allows you to add MailPoet\'s forms in many places, and in Facebook.'),
		'review' 			=> __('Very powerful, if not a quirky user interface.'),
		'plugin_url' 		=> '',
		'author_url' 		=> 'http://clicky.me/hybrid-connect',
		'purchase_url' 		=> '',
		'version' 			=> '',
		'official' 			=> 'no',
		'on_wordpress.org' 	=> 'no',
		'free' 				=> 'no',
		'service' 			=> 'yes',
		'premium_offer' 	=> '',
	),
	
	array(
		'name' 				=> 'Magic Action Box: Pretty forms in post',
		'search' 			=> 'Magic Action Box: pretty forms in post',
		'thumbnail' 		=> 'magic-action-box.png',
		'description' 		=> __('This free plugin allows you to design and position a form at the beginning or bottom of a post.'),
		'review' 			=> __('It\'s free, and has proven popular with our users.'),
		'plugin_url' 		=> '',
		'author_url' 		=> 'http://clicky.me/magic-action-box',
		'purchase_url' 		=> '',
		'version' 			=> '',
		'official' 			=> 'no',
		'on_wordpress.org' 	=> 'no',
		'free' 				=> 'no',
		'service' 			=> 'yes',
		'premium_offer' 	=> '',
	),
	
	array(
		'name' 				=> 'Optin Revolution: Popup form',
		'search' 			=> 'Optin Revolution: popup form',
		'thumbnail' 		=> 'optin-revolution.png',
		'description' 		=> __('This free plugin allows you to put a form in a popup, that\'s it.'),
		'review' 			=> __('This is the free version of a more powerful Premium version.'),
		'plugin_url' 		=> '',
		'author_url' 		=> 'http://clicky.me/optin-revolution',
		'purchase_url' 		=> '',
		'version' 			=> '',
		'official' 			=> 'no',
		'on_wordpress.org' 	=> 'no',
		'free' 				=> 'no',
		'service' 			=> 'yes',
		'premium_offer' 	=> '',
	),
	
	array(
		'name' 				=> 'Ultimate Coming Soon Page',
		'search' 			=> 'Ultimate Coming Soon Page',
		'thumbnail' 		=> 'ultimate-coming-soon.png',
		'description' 		=> __('Your new site is not yet launched? Put a coming soon page with a form to capture emails with this Premium plugin.'),
		'review' 			=> __('A well designed plugin for a simple idea.'),
		'plugin_url' 		=> '',
		'author_url' 		=> 'http://clicky.me/ultimate-coming-soon-page',
		'purchase_url' 		=> '',
		'version' 			=> '',
		'official' 			=> 'no',
		'on_wordpress.org' 	=> 'no',
		'free' 				=> 'no',
		'service' 			=> 'yes',
		'premium_offer' 	=> '',
	),
	
	array(
		'name' 				=> 'Easy Digital Downloads - MailPoet',
		'search' 			=> 'Easy Digital Downloads - MailPoet',
		'thumbnail' 		=> 'easy-digital-downloads.png',
		'description' 		=> __('This extension integrates Easy Digital Downloads with MailPoet by providing an option for your customers to signup for your newsletter while purchasing from your digital store.'),
		'review' 			=> '',
		'plugin_url' 		=> '',
		'author_url' 		=> 'https://easydigitaldownloads.com',
		'purchase_url' 		=> 'https://easydigitaldownloads.com/extensions/wysija/',
		'version' 			=> '1.1.2',
		'official' 			=> 'no',
		'on_wordpress.org' 	=> 'no',
		'free' 				=> 'no',
		'service' 			=> 'no',
		'requires' 			=> 'easy-digital-downloads/easy-digital-downloads.php',
		'premium_offer' 	=> '',
	),
	
	array(
		'name' 				=> 'Ninja Forms',
		'search' 			=> 'Ninja Forms',
		'thumbnail' 		=> 'ninja-forms.png',
		'description' 		=> __('Quickly create newsletter signup forms for your MailPoet mailing lists using the power and flexibility that Ninja Forms provides.'),
		'review' 			=> '',
		'plugin_url' 		=> 'ninja-forms-mailpoet/nf-mailpoet.php',
		'author_url' 		=> 'http://ninjaforms.com',
		'purchase_url' 		=> 'http://ninjaforms.com/downloads/mailpoet/',
		'version' 			=> '1.0.1',
		'official' 			=> 'no',
		'on_wordpress.org' 	=> 'no',
		'free' 				=> 'no',
		'service' 			=> 'no',
		'requires' 			=> 'ninja-forms/ninja-forms.php',
		'premium_offer' 	=> '',
	),
	
	/*array(
		'name' 				=> 'WangGuard: block fake signups',
		'search' 			=> 'WangGuard: block fake signups',
		'thumbnail' 		=> 'wangguard.png',
		'description' 		=> __('This plugin blocks spam signups to your site. Connect it to MailPoet with an additional add-on.'),
		'review' 			=> __('If you have this problem, then this is your solution. Totally free too.'),
		'plugin_url' 		=> '',
		'author_url' 		=> 'http://clicky.me/wangguard-plugin',
		'purchase_url' 		=> '',
		'version' 			=> '',
		'official' 			=> 'no',
		'on_wordpress.org' 	=> 'yes',
		'free' 				=> 'yes',
		'service' 			=> 'yes',
		'premium_offer' 	=> '',
	),*/

);
?>